export enum ErrorCodesEnum {
  NO_DRIVERS_AVAILABLE = "NO_DRIVERS_AVAILABLE",
  INVALID_RIDE = "INVALID_RIDE",
  RIDE_NOT_COMPLETED = "RIDE_NOT_COMPLETED",
}

export enum CommandsEnum {
  ADD_DRIVER = "ADD_DRIVER",
  ADD_RIDER = "ADD_RIDER",
  MATCH = "MATCH",
  START_RIDE = "START_RIDE",
  STOP_RIDE = "STOP_RIDE",
  BILL = "BILL",
}
